### ISSUE TITLE
Several Issues 

### ISSUE THREAD

**Issue by gekberlin** [ryanbateman/bvg_hacs#6]
Hi great that you're still working on this component!
I have added this custom component with hacs and if I restart hassio I do get several faults in the log:
```
Error doing job: Task exception was never retrieved
12:19:41 – (FEHLER) BVG (Berlin Public Transport) (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 12:18:41 aufgetreten und erscheint 3 mal

Error parsing information from https://jsonplaceholder.typicode.com/posts/1 - timeout() got an unexpected keyword argument 'loop'
12:19:41 – (FEHLER) BVG (Berlin Public Transport) (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 12:18:11 aufgetreten und erscheint 4 mal

Error adding entities for domain switch with platform bvg_berlin_public_transport
12:18:11 – (FEHLER) Schalter (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 12:18:11 aufgetreten und erscheint 2 mal

Error adding entities for domain binary_sensor with platform bvg_berlin_public_transport
12:18:11 – (FEHLER) Binärsensor (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 12:18:11 aufgetreten und erscheint 2 mal

Error while setting up bvg_berlin_public_transport platform for sensor
12:18:11 – (FEHLER) Sensor
```

I'm not quite sure what to do. Any suggestions?
Thats my config.yaml:

```
sensor:

  - platform: bvg_berlin_public_transport
    name: F***.
    stop_id: "9000*****3"
    direction: 
      - "S+U Berlin Hauptbahnhof"
    walking_distance: 5
```

**Comment by bloneu** [comment]
The configuration i use looks like this (works on HA 2022.10):

<pre>sensor Walter:
  - platform: bvg_berlin_public_transport
    name: U9 Walther-Schreiber-Platz
    stop_id: "900000061101"
    direction: "Osloer Str."
    walking_distance: 0</pre>

Maybe that will help.
*instead of direction: "S+U Berlin Hauptbahnhof" try  direction: "Hauptbahnhof".
