### ISSUE TITLE
Integration stopped working in HA version 2022.11

### ISSUE THREAD

**Issue by reentier** [ryanbateman/bvg_hacs#7]
Hi,

since the update to version 2022.11.0 of HA this integration is not working anymore on my installation.

I am getting these errors:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:249
Integration: Sensor (documentation, issues)
First occurred: 08:05:22 (1 occurrences)
Last logged: 08:05:22

Error while setting up bvg_berlin_public_transport platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 278, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in async_create_setup_task
    return platform.async_setup_entry(  # type: ignore[union-attr]
AttributeError: module 'custom_components.bvg_berlin_public_transport.sensor' has no attribute 'async_setup_entry'

Logger: homeassistant.components.binary_sensor
Source: custom_components/bvg_berlin_public_transport/binary_sensor.py:33
Integration: Binärsensor (documentation, issues)
First occurred: 08:05:22 (2 occurrences)
Last logged: 08:05:22

Error adding entities for domain binary_sensor with platform bvg_berlin_public_transport
Error while setting up bvg_berlin_public_transport platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/bvg_berlin_public_transport/binary_sensor.py", line 33, in is_on
    return self.coordinator.data.get("title", "") == "foo"
AttributeError: 'NoneType' object has no attribute 'get'

Logger: homeassistant.components.switch
Source: custom_components/bvg_berlin_public_transport/switch.py:43
Integration: Schalter (documentation, issues)
First occurred: 08:05:23 (2 occurrences)
Last logged: 08:05:23

Error adding entities for domain switch with platform bvg_berlin_public_transport
Error while setting up bvg_berlin_public_transport platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/bvg_berlin_public_transport/switch.py", line 43, in is_on
    return self.coordinator.data.get("title", "") == "foo"
AttributeError: 'NoneType' object has no attribute 'get'

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bvg_berlin_public_transport
Source: custom_components/bvg_berlin_public_transport/api.py:29
Integration: BVG (Berlin Public Transport) (documentation, issues)
First occurred: 08:05:22 (3 occurrences)
Last logged: 08:06:24

Error parsing information from https://jsonplaceholder.typicode.com/posts/1 - timeout() got an unexpected keyword argument 'loop'

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/bvg_berlin_public_transport/binary_sensor.py:33
Integration: BVG (Berlin Public Transport) (documentation, issues)
First occurred: 08:06:12 (2 occurrences)
Last logged: 08:06:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/bvg_berlin_public_transport/binary_sensor.py", line 33, in is_on
    return self.coordinator.data.get("title", "") == "foo"
AttributeError: 'NoneType' object has no attribute 'get'

Can anybody help me to fix this errors?

Thanks in Advance

**Comment by Quadrubo** [comment]
I also run into this error, just tried to install it, anything I can do to help troubleshooting?
